#!/bin/bash

# Provide a personal access token that can
# access the source and target repositories.
# This is how you authorize with the GitHub API.
# https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line
GH_TOKEN=$1

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

JSON_FILE="${SCRIPT_DIR}/apian-issue-labels.json"

#
if [[ "$1" == ""  ]]
then
    echo "usage: $0 <github-access-token>"
    exit
fi

echo $SCRIPT_DIR
echo $JSON_FILE
echo


destApianRepos=("Ace" "Apian.Net" "Beam.Cli" "Beam.Unity" "BeamGameCode" "NotUnityEngine" "P2pNet" "Start-Here" "UniLog")

for repo in "${destApianRepos[@]}"; do

    echo Processing $repo...
    $SCRIPT_DIR/upload-apian-issue-labels $GH_TOKEN $repo $JSON_FILE

done